<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="INBASDPC06818" ignored="0" name="US" tests="4" failures="2" timestamp="18 Sep 2019 09:24:21 GMT" time="49.848" errors="0">
  <testcase name="validate_footerlinks" time="0.011" classname="tests.US">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at tests.US.validate_footerlinks(US.java:52)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 14 stack frames]]>
    </failure>
  </testcase> <!-- validate_footerlinks -->
  <testcase name="validate_sidemenulinks" time="0.011" classname="tests.US">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at tests.US.validate_sidemenulinks(US.java:64)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 14 stack frames]]>
    </failure>
  </testcase> <!-- validate_sidemenulinks -->
  <testcase name="validate_topmenulinks" time="0.049" classname="tests.US"/>
  <testcase name="signin" time="31.974" classname="tests.US"/>
</testsuite> <!-- US -->
